/**
 * Generate src/generated/version.ts from package.json version.
 *
 * Run manually:   node scripts/generate-version.mjs
 * Runs automatically via: prebuild, predev, and version lifecycle hooks.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf-8'));
const version = pkg.version;

if (!/^[0-9a-zA-Z._+-]+$/.test(version)) {
  console.error(`Invalid version string: "${version}"`);
  process.exit(1);
}

const outDir = resolve(root, 'src', 'generated');
mkdirSync(outDir, { recursive: true });

const content = `// Auto-generated by scripts/generate-version.mjs — do not edit manually
export const APP_VERSION = '${version}';
`;

writeFileSync(resolve(outDir, 'version.ts'), content, 'utf-8');

console.log(`Generated src/generated/version.ts → ${version}`);
